import { Router } from 'express';
const subscriptionRouter = Router();
subscriptionRouter.get('/',(req,res)=>res.send({title :"GET all subscriptions"}));
subscriptionRouter.get('/:id',(req,res)=>res.send({title :"GET all subscription details"}));
subscriptionRouter.post('/',(req,res)=>res.send({title :"Create  subscription"}));
subscriptionRouter.put('/:id',(req,res)=>res.send({title :"UPDATE all subscription"}));
subscriptionRouter.delete('/:id',(req,res)=>res.send({title :"DELETE  subscription"}));
subscriptionRouter.get('/users/:id',(req,res)=>res.send({title :"GET all  user subscription"}));
subscriptionRouter.get('/:id/cancel',(req,res)=>res.send({title :"CANCEl subscription"}));
subscriptionRouter.get('/upcoming-renewals',(req,res)=>res.send({title :"GET upcomin renewals "}));
export default subscriptionRouter;